import type { Metadata } from "next";
import "./globals.css";
import "./gg.css";
import "./startgame.css";
import "./countdown.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import "./game.css";
import "./hangman.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`antialiased`}>
        <div id="__next">{children}</div>
      </body>
    </html>
  );
}
